[package]
name = "acad-wasm"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
acad-model.workspace = true
acad-dwg.workspace = true
acad-dxf.workspace = true
acad-cmd = { path = "../acad-cmd" }
acad-render.workspace = true
acad-app = { path = "../acad-app" }
wasm-bindgen = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["ImageData"] }
