[workspace]
members = ["crates/acad-model", "crates/acad-corpus", "crates/acad-dxf", "crates/acad-render", "crates/acad-app"]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.88"

[workspace.dependencies]
acad-model = { path = "crates/acad-model" }
acad-dxf = { path = "crates/acad-dxf" }
acad-render = { path = "crates/acad-render" }
