[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 64"]

[project]
name = "cad_audit"
version = "0.1.0"
dependencies = [
  "nvidia-nat[langchain]~=1.9",
]
requires-python = ">=3.11,<3.14"
description = "Custom NeMo Agent Toolkit Workflow"
classifiers = ["Programming Language :: Python"]



[project.entry-points.'nat.components']
cad_audit = "cad_audit.register"
