[package]
name = "acad-cmd"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
acad-model.workspace = true

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
acad-dwg.workspace = true
serde_json = "1"

[build-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
