use acad_model::Point;

#[derive(Debug, Clone, Copy)]
pub(crate) enum Transform {
    Translate(Point),
    Rotate { base: Point, degrees: f64 },
    Scale { base: Point, factor: f64 },
}

#[derive(Debug, Clone, PartialEq)]
pub(crate) enum InputState {
    Command,
    LineStart,
    LineNext(Point),
    CircleCenter,
    CircleRadius(Point),
    Point,
    ArcStart,
    ArcMiddle(Point),
    ArcEnd(Point, Point),
    LoadLibrary,
    ShapeName,
    ShapeOrigin(u16),
    ShapeHeight(u16, Point),
    ShapeRotation(u16, Point, f64),
    TextOrigin,
    TextHeight(Point),
    TextRotation(Point, f64),
    TextValue(Point, f64, f64),
    InsertName,
    InsertOrigin(String, bool),
    InsertXScale(String, Point),
    InsertYScale(String, Point, f64),
    InsertRotation(String, Point, f64, f64),
    BlockName,
    BlockBase(String),
    BlockSelection(String, Point),
    WblockPath,
    WblockName(String),
    WblockBase(String),
    WblockSelection(String, Point),
    HelpCommand,
    MenuFile,
    FilesMenu,
    FilesDrive(crate::FilesFilter),
    FilesListSpecification,
    FilesDeleteSpecification,
    FilesRenameSource,
    FilesRenameDestination(String),
    Delay,
    UnitsFormat,
    UnitsPrecision(acad_model::UnitFormat),
    SavePath,
    Base,
    Axis,
    Snap,
    Grid,
    Ortho,
    Fill,
    LimitsMin,
    LimitsMax(Point),
    Layer,
    ColorValue,
    ColorTargetLayer,
    Zoom,
    ZoomCenter,
    ZoomCenterHeight(Point),
    ZoomWindowMin,
    ZoomWindowMax(Point),
    PanCenter,
    EditSelection(EditCommand),
    EditBase(EditCommand, Vec<usize>),
    EditValue(EditCommand, Vec<usize>, Point),
    Displacement(EditCommand),
    SecondPoint(EditCommand, Point),
    DisplacedSelection(EditCommand, Point),
    ArraySelection,
    ArrayMode(Vec<usize>),
    ArrayCircularCenter(Vec<usize>),
    ArrayCircularAngle(Vec<usize>, Point),
    ArrayCircularItems(Vec<usize>, Point, f64),
    ArrayRows(Vec<usize>),
    ArrayColumns(Vec<usize>, usize),
    ArrayRowSpacing(Vec<usize>, usize, usize),
    ArrayColumnSpacing(Vec<usize>, usize, usize, ArraySpacingInput),
    ChangeSelection,
    ChangeIntersection(Vec<usize>),
    ChangeLayer(Vec<usize>),
    ChangeInsertAngle(Vec<usize>),
    FilletSelection,
    FilletRadius(Vec<usize>),
    BreakSelection,
    BreakFirstPoint(Vec<usize>),
    BreakSecondPoint(Vec<usize>, Point),
    DistanceFirstPoint,
    DistanceSecondPoint(Point),
    IdPoint,
    SolidFirstPoint,
    SolidSecondPoint(Point),
    SolidThirdPoint(Point, Point),
    SolidFourthPoint(Point, Point, Point),
    TraceWidth,
    TraceStart(f64),
    TraceNext(f64, Vec<Point>),
    AreaFirstPoint,
    AreaNextPoint(Vec<Point>),
    AreaSelection,
    RepeatColumns,
    RepeatRows(u16),
    RepeatColumnSpacing(u16, u16, Point),
    RepeatRowSpacing(u16, u16, f64, Point, RepeatDistanceInput),
    DimFirstExtension,
    DimIntersection(Point),
    DimSecondExtension(Point, Point),
    DimText(Point, Point, Point),
    HatchPattern,
    HatchScale(String),
    HatchAngle(String, f64),
    HatchSelection(String, f64, f64),
    HatchWindowFirst(String, f64, f64),
    HatchWindowSecond(String, f64, f64, Point),
    SketchIncrement,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum EditCommand {
    Erase,
    Move,
    Copy,
    Rotate,
    Scale,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum RepeatDistanceInput {
    Number,
    Point,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub(crate) enum ArraySpacingInput {
    Number(f64),
    Point(Point),
}

impl InputState {
    pub(crate) fn prompt(&self) -> &'static str {
        match self {
            Self::Command => "Command",
            Self::LineStart => "LINE: first point",
            Self::LineNext(_) => "LINE: next point (Enter to finish)",
            Self::CircleCenter => "CIRCLE: center point",
            Self::CircleRadius(_) => "CIRCLE: radius",
            Self::Point => "POINT: point",
            Self::ArcStart => "ARC: start point",
            Self::ArcMiddle(_) => "ARC: second point",
            Self::ArcEnd(_, _) => "ARC: end point",
            Self::LoadLibrary => "LOAD: library name",
            Self::ShapeName => "SHAPE: shape name",
            Self::ShapeOrigin(_) => "SHAPE: insertion point",
            Self::ShapeHeight(_, _) => "SHAPE: height",
            Self::ShapeRotation(_, _, _) => "SHAPE: rotation angle",
            Self::TextOrigin => "TEXT: start point",
            Self::TextHeight(_) => "TEXT: height",
            Self::TextRotation(_, _) => "TEXT: rotation angle",
            Self::TextValue(_, _, _) => "TEXT: value",
            Self::InsertName => "INSERT: block name",
            Self::InsertOrigin(_, _) => "INSERT: insertion point",
            Self::InsertXScale(_, _) => "INSERT: X scale or opposite corner x,y (Enter for 1)",
            Self::InsertYScale(_, _, _) => "INSERT: Y scale (Enter for X scale)",
            Self::InsertRotation(_, _, _, _) => "INSERT: rotation angle (Enter for 0)",
            Self::BlockName => "BLOCK: block name",
            Self::BlockBase(_) => "BLOCK: insertion base point",
            Self::BlockSelection(_, _) => "BLOCK: entity numbers, ALL or LAST",
            Self::WblockPath => "WBLOCK: output file name",
            Self::WblockName(_) => "WBLOCK: block name (* for entire drawing)",
            Self::WblockBase(_) => "WBLOCK: insertion base point",
            Self::WblockSelection(_, _) => "WBLOCK: entity numbers, ALL, or LAST",
            Self::HelpCommand => "Command name (RETURN for list)",
            Self::MenuFile => "File name",
            Self::FilesMenu => "FILES: selection (0–7)",
            Self::FilesDrive(_) => "FILES: drive letter (A–Z)",
            Self::FilesListSpecification => "FILES: file specification",
            Self::FilesDeleteSpecification => "FILES: file deletion specification",
            Self::FilesRenameSource => "FILES: current filename",
            Self::FilesRenameDestination(_) => "FILES: new filename",
            Self::Delay => "DELAY: duration",
            Self::UnitsFormat => "UNITS: choice, 1 to 4",
            Self::UnitsPrecision(acad_model::UnitFormat::Architectural) => {
                "UNITS: denominator (1, 2, 4, 8, 16, 32, or 64)"
            }
            Self::UnitsPrecision(_) => "UNITS: digits to right of decimal point (0 to 8)",
            Self::SavePath => "SAVE: output file",
            Self::Base => "BASE: x,y",
            Self::Axis => "AXIS: ON, OFF, or tick spacing (X for snap multiples)",
            Self::Snap => "SNAP: spacing",
            Self::Grid => "GRID: spacing",
            Self::Ortho => "ORTHO: ON or OFF",
            Self::Fill => "FILL: ON or OFF",
            Self::LimitsMin => "LIMITS: lower-left",
            Self::LimitsMax(_) => "LIMITS: upper-right",
            Self::Layer => "LAYER: index",
            Self::ColorValue => "COLOR: color index",
            Self::ColorTargetLayer => "COLOR: next current layer (Enter to finish)",
            Self::Zoom => "ZOOM: factor, E, W, C or P",
            Self::ZoomCenter => "ZOOM CENTER: x,y",
            Self::ZoomCenterHeight(_) => "ZOOM CENTER: view height",
            Self::ZoomWindowMin => "ZOOM WINDOW: lower-left",
            Self::ZoomWindowMax(_) => "ZOOM WINDOW: upper-right",
            Self::PanCenter => "PAN: new view center x,y",
            Self::EditSelection(EditCommand::Erase) => "ERASE: entity numbers or ALL",
            Self::EditSelection(EditCommand::Move | EditCommand::Copy) => {
                unreachable!("MOVE and COPY select after displacement")
            }
            Self::EditSelection(EditCommand::Rotate) => "ROTATE: entity numbers or ALL",
            Self::EditSelection(EditCommand::Scale) => "SCALE: entity numbers or ALL",
            Self::EditBase(EditCommand::Move | EditCommand::Copy, _) => {
                unreachable!("MOVE and COPY use displacement prompts")
            }
            Self::EditBase(EditCommand::Rotate, _) => "ROTATE: base point x,y",
            Self::EditBase(EditCommand::Scale, _) => "SCALE: base point x,y",
            Self::EditBase(EditCommand::Erase, _) => "ERASE: selection",
            Self::EditValue(EditCommand::Rotate, _, _) => "ROTATE: angle in degrees",
            Self::EditValue(EditCommand::Scale, _, _) => "SCALE: factor (>0)",
            Self::EditValue(EditCommand::Move | EditCommand::Copy, _, _) => {
                unreachable!("MOVE and COPY use displacement prompts")
            }
            Self::EditValue(_, _, _) => "edit: value",
            Self::Displacement(EditCommand::Move) => "MOVE: displacement or first point x,y",
            Self::Displacement(EditCommand::Copy) => "COPY: displacement or first point x,y",
            Self::SecondPoint(EditCommand::Move, _) => {
                "MOVE: second point (Enter for displacement)"
            }
            Self::SecondPoint(EditCommand::Copy, _) => {
                "COPY: second point (Enter for displacement)"
            }
            Self::DisplacedSelection(EditCommand::Move, _) => "MOVE: select objects, ALL or LAST",
            Self::DisplacedSelection(EditCommand::Copy, _) => "COPY: select objects, ALL or LAST",
            Self::Displacement(_) | Self::SecondPoint(_, _) | Self::DisplacedSelection(_, _) => {
                unreachable!("only MOVE and COPY use displacement prompts")
            }
            Self::ArraySelection => "ARRAY: entity numbers or ALL",
            Self::ArrayMode(_) => "ARRAY: rectangular or circular (R/C)",
            Self::ArrayCircularCenter(_) => "ARRAY: center point",
            Self::ArrayCircularAngle(_, _) => "ARRAY: angle between items",
            Self::ArrayCircularItems(_, _, _) => "ARRAY: number of items",
            Self::ArrayRows(_) => "ARRAY: number of rows",
            Self::ArrayColumns(_, _) => "ARRAY: number of columns",
            Self::ArrayRowSpacing(_, _, _) => "ARRAY: row spacing",
            Self::ArrayColumnSpacing(_, _, _, _) => "ARRAY: column spacing",
            Self::ChangeSelection => "CHANGE: entity numbers or ALL",
            Self::ChangeIntersection(_) => "CHANGE: intersection point or L",
            Self::ChangeLayer(_) => "CHANGE: new layer index",
            Self::ChangeInsertAngle(_) => "CHANGE: new angle (Enter keeps current)",
            Self::FilletSelection => "FILLET: select two LINE entities",
            Self::FilletRadius(_) => "FILLET: radius",
            Self::BreakSelection => "BREAK: one LINE, ARC or CIRCLE entity",
            Self::BreakFirstPoint(_) => "BREAK: first point",
            Self::BreakSecondPoint(_, _) => "BREAK: second point",
            Self::DistanceFirstPoint => "DIST: first point",
            Self::DistanceSecondPoint(_) => "DIST: second point",
            Self::IdPoint => "ID: point",
            Self::SolidFirstPoint => "SOLID: first point",
            Self::SolidSecondPoint(_) => "SOLID: second point",
            Self::SolidThirdPoint(_, _) => "SOLID: third point (Enter to finish)",
            Self::SolidFourthPoint(_, _, _) => "SOLID: fourth point",
            Self::TraceWidth => "TRACE: width",
            Self::TraceStart(_) => "TRACE: first point",
            Self::TraceNext(_, _) => "TRACE: next point (Enter to finish)",
            Self::AreaFirstPoint => "AREA: first point",
            Self::AreaNextPoint(_) => "AREA: next point (Enter to finish)",
            Self::AreaSelection => "ENTITYAREA: entity numbers or ALL",
            Self::RepeatColumns => "ENDREP: columns",
            Self::RepeatRows(_) => "ENDREP: rows",
            Self::RepeatColumnSpacing(_, _, _) => "ENDREP: column distance",
            Self::RepeatRowSpacing(_, _, _, _, _) => "ENDREP: row distance",
            Self::DimFirstExtension => "DIM: first extension line origin or (ABCT)",
            Self::DimIntersection(_) => "DIM: dimension line intersection",
            Self::DimSecondExtension(_, _) => "DIM: second extension line origin",
            Self::DimText(_, _, _) => "DIM: dimension text",
            Self::HatchPattern => "HATCH: pattern (name,style / U / ?)",
            Self::HatchScale(_) => "HATCH: scale for pattern {1}",
            Self::HatchAngle(_, _) => "HATCH: angle for pattern {0}",
            Self::HatchSelection(_, _, _) => "HATCH: select objects on Window or Last",
            Self::HatchWindowFirst(_, _, _) => "HATCH: lower left corner",
            Self::HatchWindowSecond(_, _, _, _) => "HATCH: upper right corner",
            Self::SketchIncrement => "SKETCH: record increment",
        }
    }
}
