mod check;
use check::{classify, Verdict};
use sha2::{Digest, Sha256};
use std::{fs, path::Path};

fn main() -> std::io::Result<()> {
    let root = Path::new("corpus");
    let mut rows: Vec<String> = Vec::new();
    let mut dirs: Vec<_> = fs::read_dir(root)?.filter_map(Result::ok)
        .filter(|e| e.path().is_dir() && e.file_name() != "raw").collect();
    dirs.sort_by_key(|e| e.file_name());
    for dir in dirs {
        let disk = dir.file_name().to_string_lossy().to_string();
        let mut files: Vec<_> = fs::read_dir(dir.path())?.filter_map(Result::ok).collect();
        files.sort_by_key(|e| e.file_name());
        for f in files {
            let name = f.file_name().to_string_lossy().to_string();
            let bytes = fs::read(f.path())?;
            let sha = format!("{:x}", Sha256::digest(&bytes));
            let verdict = match classify(&name, &bytes) {
                Verdict::Ok => "ok".to_string(),
                Verdict::Binary => "binary".to_string(),
                Verdict::CorruptAt(o) => format!("corrupt_at_{o}"),
            };
            rows.push(format!(
                "[[file]]\ndisk = \"{disk}\"\nname = \"{name}\"\nbytes = {}\nsha256 = \"{sha}\"\nverdict = \"{verdict}\"\n",
                bytes.len()));
        }
    }
    let body = format!("# Generated by `cargo run -p acad-corpus`. Do not edit by hand.\n\n{}", rows.join("\n"));
    fs::write(root.join("manifest.toml"), body)?;
    println!("wrote corpus/manifest.toml ({} files)", rows.len());
    Ok(())
}
