//! Engine limits and execution policies for memory safety and format compliance.

/// Tunable engine resource limits across parsing, expansion, rendering, and commands.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EngineLimits {
    /// Maximum group/REPEAT nesting depth.
    pub max_group_depth: usize,
    /// Maximum stored entity hierarchy depth (e.g. layer wrappers, repeats).
    pub max_stored_depth: usize,
    /// Maximum recursive block INSERT nesting depth.
    pub max_insert_depth: usize,
    /// Maximum traversal visits / safety budget for entity graph scans.
    pub max_traversal_visits: usize,
    /// Maximum entities generated by an ARRAY command or similar generation step.
    pub max_array_entities: usize,
    /// Whole-frame aggregate rendering work units.
    pub frame_work_limit: usize,
    /// Fixed setup cost per emitted rendering primitive.
    pub primitive_setup_units: usize,
    /// Maximum HATCH sweep rows and dash cycle evaluations.
    pub max_hatch_work: usize,
    /// Maximum distinct diagnostics retained per render pass.
    pub max_diagnostics: usize,
    /// Maximum stored records in a single drawing.
    pub max_stored_records: usize,
}

impl EngineLimits {
    /// Exact 1983 AutoCAD 1.4 / DOS-parity limits.
    pub const DEFAULT_1983: Self = Self {
        max_group_depth: 64,
        max_stored_depth: 256,
        max_insert_depth: 16,
        max_traversal_visits: 100_000,
        max_array_entities: 100_000,
        frame_work_limit: 1_000_000,
        primitive_setup_units: 4,
        max_hatch_work: 10_000_000,
        max_diagnostics: 64,
        max_stored_records: 65_535,
    };

    /// High-capacity profile for modern large-scale CAD models.
    pub const MODERN: Self = Self {
        max_group_depth: 1024,
        max_stored_depth: 4096,
        max_insert_depth: 128,
        max_traversal_visits: 10_000_000,
        max_array_entities: 10_000_000,
        frame_work_limit: 100_000_000,
        primitive_setup_units: 4,
        max_hatch_work: 500_000_000,
        max_diagnostics: 1024,
        max_stored_records: usize::MAX,
    };
}

impl Default for EngineLimits {
    fn default() -> Self {
        Self::DEFAULT_1983
    }
}
